### ISSUE TITLE
Substraat klassen mossen

### ISSUE THREAD

**Issue by woutervanlanduyt** [woutervanlanduyt/moss-change#4]
bij de substraatklassen mossen zit nog een extra waarde die de voorkeur voor de substraten weergeeft volgens BryoAtt (Hill et al 2007). Die varieert van 1-3, 1 betekent 'A rare habitat or substrate for the species', 2 'An occasional habitat or substrate for the species' en 3 'A normal habitat or substrate for the species'. Ik denk dat we voor de analyse best enkel met waarde 3 werken.

Deze extra waarde is te vinden in Userflorabank in de tabel relTaxonTaxonKenmerkWaarde in de kolom Omschrijving.

Ik vermoed dat dit ergens moet aangepast worden in regel 50 en dat er daarna een filter op die waarde moet toegepast worden.

**Comment by hansvancalster** [comment]
Zou in orde moeten zijn. Ik heb nog geen tijd gehad om de paper te lezen en de methoden uit te schrijven. Misschien als ik volgende week een gaatje vind.
